<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MasterAreaOfficeTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('master_area_office')->delete();
        
        \DB::table('master_area_office')->insert(array (
            0 => 
            array (
                'id' => 1,
                'master_state_fdc_id' => 1,
                'title' => 'FD Karnal South',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'master_state_fdc_id' => 1,
                'title' => 'FD Karnal GT Road Bt',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'master_state_fdc_id' => 2,
                'title' => 'FD Mohali North',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'master_state_fdc_id' => 2,
                'title' => 'FD Mohali Central',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'master_state_fdc_id' => 2,
                'title' => 'FD Mohali South',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'master_state_fdc_id' => 3,
                'title' => 'FD Kota',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'master_state_fdc_id' => 3,
                'title' => 'FD Jaipur',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'master_state_fdc_id' => 4,
                'title' => 'FD Jodhpur',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'master_state_fdc_id' => 4,
                'title' => 'FD Udaipur',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'master_state_fdc_id' => 4,
                'title' => 'FD Bikaner',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'master_state_fdc_id' => 5,
                'title' => 'FD Bundelkhand',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'master_state_fdc_id' => 5,
                'title' => 'FD Lucknow',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'master_state_fdc_id' => 6,
                'title' => 'FD Gorakhpur',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'master_state_fdc_id' => 6,
                'title' => 'FD Varanasi',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'master_state_fdc_id' => 7,
                'title' => 'FD N Delhi Potato',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'master_state_fdc_id' => 7,
                'title' => 'FD N Delhi Sugarcane',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'master_state_fdc_id' => 8,
                'title' => 'FD Patna Kosi',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'master_state_fdc_id' => 8,
                'title' => 'FD Patna North',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'master_state_fdc_id' => 8,
                'title' => 'FD Patna South',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'master_state_fdc_id' => 9,
                'title' => 'FD Ranchi',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'master_state_fdc_id' => 10,
                'title' => 'FD North East',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'master_state_fdc_id' => 11,
                'title' => 'FD Calcutta',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'master_state_fdc_id' => 11,
                'title' => 'FD North Bengal',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'master_state_fdc_id' => 12,
                'title' => 'FD NCG',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'master_state_fdc_id' => 12,
                'title' => 'FD RCG',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'master_state_fdc_id' => 13,
                'title' => 'FD Jabalpur',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'master_state_fdc_id' => 13,
                'title' => 'FD Gwalior',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'master_state_fdc_id' => 13,
                'title' => 'FD Satna',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'master_state_fdc_id' => 14,
                'title' => 'FD Bhopal',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'master_state_fdc_id' => 14,
                'title' => 'FD Mandsaur',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'master_state_fdc_id' => 14,
                'title' => 'FD Indore',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'master_state_fdc_id' => 15,
                'title' => 'FD Bhubaneshwar',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'master_state_fdc_id' => 16,
                'title' => 'FD South Gujarat',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'master_state_fdc_id' => 16,
                'title' => 'FD Rajkot',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'master_state_fdc_id' => 16,
                'title' => 'FD North Gujarat',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'master_state_fdc_id' => 17,
                'title' => 'FD Bangalore',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'master_state_fdc_id' => 17,
                'title' => 'FD Hubli',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'master_state_fdc_id' => 17,
                'title' => 'FD Bellary',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'master_state_fdc_id' => 18,
                'title' => 'FD Marathwada',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'master_state_fdc_id' => 18,
                'title' => 'FD Nagpur',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'master_state_fdc_id' => 19,
                'title' => 'FD Pune',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'master_state_fdc_id' => 19,
                'title' => 'FD Nasik',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'master_state_fdc_id' => 20,
                'title' => 'FD Tirupati',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'master_state_fdc_id' => 20,
                'title' => 'FD Vijaywada',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'master_state_fdc_id' => 21,
                'title' => 'FD Madurai',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'master_state_fdc_id' => 21,
                'title' => 'FD Chennai',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'master_state_fdc_id' => 22,
                'title' => 'FD Telangana North',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'master_state_fdc_id' => 22,
                'title' => 'FD Telangana South',
                'is_active' => '',
                'created_at' => NULL,
                'created_by' => NULL,
                'updated_at' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ),
        ));
        
        
    }
}